name: coreshop
version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=CoreShop
    volumes:
      - redis:/data

  mysql:
    image: mysql:5.7.44
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4  --collation-server=utf8mb4_unicode_ci --lower_case_table_names=2
    environment:
      - MYSQL_DATABASE=CoreShop
      - MYSQL_ROOT_PASSWORD=CoreShop
    volumes:
      - mysql:/var/lib/mysql

volumes:
  redis:
  mysql:
